version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Ajmna1437,
      POSTGRES_DB: vca-tech
    networks:
      - testingNetwork
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpw
      POSTGRES_DB: vca-tech-test
    networks:
      - testingNetwork
networks:
  testingNetwork: